### ISSUE TITLE
Suggestions to avoid duplicate deduction for phase two

### ISSUE THREAD

**Issue by tianhanl** [gabroo/csci499_gabroo#3]
Have you been participating in the review process for the phase 2? Both functionality and reviews you given to other students will be taken into account for phase 2 grading.

KVStore needs to support concurrent access.
https://github.com/gabroo/csci499_gabroo/blob/e23bea46ef050813e7a835a4a6fc8e349b949ae9/kvstore/store.h#L18
> -5 for concurrency not supported

Missing parameter validation.
https://github.com/gabroo/csci499_gabroo/blob/e23bea46ef050813e7a835a4a6fc8e349b949ae9/warble/functions.cc#L57
> -3, reply with invalid ID should fail

**Comment by gabroo** [comment]
Added mutex to KVStore class and the appropriate locks to each operation. Also fixed the invalid ID issue in warble. [#4]
